version: '3'
services:
 mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: SpringBootDemoDB
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      - mynetwork
 spring-app:
    container_name: spring-app
    ports:
      - "8080:8080"
    build:
     context: ./
     dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3307/SpringBootDemoDB?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - mydata:/var/lib/mysql
    links:
      - mysqldb
    networks:
      - mynetwork
networks:
  mynetwork:
   driver: bridge
volumes:
  mydata:
